apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: myapp-2
    key: value
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-2
    matchExpressions:
    - {key: app, operator: In, values: [myapp-2] }
  template:
    metadata:
      labels:
        app: myapp-2
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
          - containerPort: 80