replicaCount: 3

image:
  repository: rabbitmq
  tag: "management-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "900"

persistence:
  enabled: true
  storageClass: "gp2"


service:
  management:
    type: LoadBalancer
    port: 15672
  amqp:
    type: LoadBalancer
    port: 5672

rabbitmq:
  adminUser: "admin"
  adminPassword: "YWRtaW4tcGFzc3dvcmQ=" # Base64 encoded #"admin@123"
  erlangCookie: "c29tZS1zZWNyZXQtY29va2ll" # Base64 encoded"some-secret-cookie"

livenessProbe:
  httpGet:
    path: /api/health/ready
    port: management
  initialDelaySeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /api/health/ready
    port: management
  initialDelaySeconds: 10
  timeoutSeconds: 3