apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
data:
  username: {{ .Values.rabbitmq.adminUser | b64enc }}
  password: {{ .Values.rabbitmq.adminPassword | b64enc }}
  erlang-cookie: {{ .Values.rabbitmq.erlangCookie | b64enc }}