apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
stringData:
  username: {{ .Values.rabbitmq.adminUser }}
  password: {{ .Values.rabbitmq.adminPassword }}
  erlang-cookie: {{ .Values.rabbitmq.erlangCookie }}