apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
spec:
  type: {{ .Values.service.management.type }}
  ports:
  - port: {{ .Values.service.management.port }}
    targetPort: 15672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-amqp
spec:
  type: {{ .Values.service.amqp.type }}
  ports:
  - port: {{ .Values.service.amqp.port }}
    targetPort: 5672
  selector:
    app: rabbitmq